platform :ios, '7.0'

target 'StaticTableViewExample', :exclusive => true do
	pod "EPSStaticTableViewController", :path => "../EPSStaticTableViewController.podspec"
end

target 'Tests', :exclusive => true do
  pod "EPSStaticTableViewController", :path => "../"
end
